# Generated by Django 5.0.6 on 2024-11-16 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataholder', '0002_alter_userinputdata_team_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user_input_data',
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='audience_reach',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='competition_level',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='competitor_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='crowdfunding_m',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='demand_level',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='investments_m',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='market_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='social_impact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='start_m',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='startup_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='team_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='team_mapping',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='team_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='team_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='tech_investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='tech_level',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userinputdata',
            name='theme_id',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField()),
                ('description', models.TextField()),
                ('project_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(600000), django.core.validators.MaxValueValidator(699999)])),
                ('is_public', models.BooleanField(default=True)),
                ('user_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataholder.userinputdata')),
            ],
        ),
        migrations.CreateModel(
            name='LSTMTimePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_social_idx', models.FloatField()),
                ('predicted_investments_m', models.FloatField()),
                ('predicted_crowdfunding_m', models.FloatField()),
                ('predicted_demand_idx', models.FloatField()),
                ('predicted_comp_idx', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataholder.project')),
            ],
        ),
        migrations.CreateModel(
            name='LSTMPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_social_idx', models.FloatField()),
                ('predicted_investments_m', models.FloatField()),
                ('predicted_crowdfunding_m', models.FloatField()),
                ('predicted_demand_idx', models.FloatField()),
                ('predicted_comp_idx', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataholder.project')),
            ],
        ),
        migrations.CreateModel(
            name='SyntheticPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_social_idx', models.FloatField()),
                ('predicted_investments_m', models.FloatField()),
                ('predicted_crowdfunding_m', models.FloatField()),
                ('predicted_demand_idx', models.FloatField()),
                ('predicted_comp_idx', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataholder.project')),
            ],
        ),
        migrations.CreateModel(
            name='SyntheticTimePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_social_idx', models.FloatField()),
                ('predicted_investments_m', models.FloatField()),
                ('predicted_crowdfunding_m', models.FloatField()),
                ('predicted_demand_idx', models.FloatField()),
                ('predicted_comp_idx', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataholder.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelPredictions',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
