# Generated by Django 5.0.6 on 2024-11-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataholder', '0004_alter_lstmprediction_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_idx', models.FloatField()),
                ('competition_idx', models.FloatField()),
                ('team_idx', models.FloatField()),
                ('tech_idx', models.FloatField()),
                ('social_idx', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indeces', to='dataholder.project')),
            ],
        ),
    ]
