# Generated by Django 5.0.6 on 2024-11-22 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataholder', '0003_remove_projects_user_input_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lstmprediction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lstm_predictions', to='dataholder.project'),
        ),
        migrations.AlterField(
            model_name='lstmtimeprediction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lstm_time_predictions', to='dataholder.project'),
        ),
        migrations.AlterField(
            model_name='syntheticprediction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_predictions', to='dataholder.project'),
        ),
        migrations.AlterField(
            model_name='synthetictimeprediction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_time_predictions', to='dataholder.project'),
        ),
    ]
